id = "material-icon-theme"
name = "Material Icon Theme"
version = "1.3.1"
schema_version = 1
authors = ["Zed Industries <support@zed.dev>"]
description = "Material Design icons."
repository = "https://github.com/zed-extensions/material-icon-theme"
